services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=mohith
      - POSTGRES_PASSWORD=mohith792916
      - POSTGRES_DB=paymenteeDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: